
#type: args

train:
  epochs: 100
  batch_size: 8 
  lr: 1.0e-3
  itr_per_epoch: 1.0e+8

diffusion:
  layers: 4 
  channels: 64 
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  is_linear: True

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "test"
  num_sample_features: 64
